import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

export const languageOptions = [
  { code: 'en', flag: '🇬🇧', label: 'English' },
  { code: 'de', flag: '🇩🇪', label: 'Deutsch' },
  { code: 'fr', flag: '🇫🇷', label: 'Francais' },
  { code: 'it', flag: '🇮🇹', label: 'Italiano' },
];

const translations = {
  en: {
    common: {
      search: 'Search',
      noData: 'No data available',
      previous: 'Previous',
      next: 'Next',
      confirm: 'Please confirm',
      areYouSure: 'Are you sure?',
      delete: 'Delete',
      cancel: 'Cancel',
      save: 'Save',
      edit: 'Edit',
      add: 'Add',
      loading: 'Loading...',
      actions: 'Actions',
      title: 'Title',
      status: 'Status',
      priority: 'Priority',
      category: 'Category',
      messages: 'Messages',
      send: 'Send',
      reconnect: 'Reconnect',
      online: 'Online',
      profile: 'Profile',
      logout: 'Log out',
      closeMenu: 'Close menu',
    },
    header: {
      welcome: 'Welcome',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      expandMenu: 'Expand menu',
      collapseMenu: 'Collapse menu',
      openMenu: 'Open menu',
      language: 'Language',
    },
    sidebar: {
      eyebrow: 'Vista Core',
      title: 'CRM Workspace',
      footer: 'Tenant panel',
      dashboard: 'Dashboard',
      kunden: 'Customers',
      projekte: 'Projects',
      tickets: 'Tickets',
      benutzer: 'Users',
      chat: 'Chat',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Sign in',
      email: 'E-Mail',
      password: 'Password',
      loginFailed: 'Sign in failed.',
      twoFactor: 'Two-Factor',
      codeSent: 'A verification code was sent to',
      codeLabel: '6-digit code',
      verify: 'Verify',
      invalidCode: 'Code is invalid or expired.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'All',
      refresh: 'Refresh',
      loading: 'Loading dashboard data...',
      error: 'Dashboard data could not be loaded.',
      empty: 'No data to display.',
      kundenAnzahl: 'Customers',
      projekteAnzahl: 'Projects',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Open tickets',
      benutzerAnzahl: 'Users',
      berichteAnzahl: 'Reports',
      aktiveProjekte: 'Active projects',
      kritischeTickets: 'Critical tickets',
    },
    kunden: {
      title: 'Customers',
      new: 'New customer',
      loading: 'Loading customers...',
      search: 'Search customer...',
      deleteTitle: 'Delete customer',
      deleteMessage: 'This record will be permanently removed. Continue?',
      saveError: 'Saving failed.',
      company: 'Company',
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Phone',
      mobilePhone: 'Phone (mobile)',
      homePhone: 'Phone (home)',
      address: 'Address',
      website: 'Website',
      notes: 'Notes',
      editTitle: 'Edit customer',
      newTitle: 'New customer',
    },
    projekte: {
      title: 'Projects',
      new: 'New project',
      loading: 'Loading projects...',
      search: 'Search project...',
      deleteTitle: 'Delete project',
      deleteMessage: 'Project will be permanently deleted. Continue?',
      saveError: 'Saving failed.',
      name: 'Name',
      description: 'Description',
      start: 'Start',
      end: 'End',
      completion: 'Completion %',
      editTitle: 'Edit project',
      newTitle: 'New project',
    },
    tickets: {
      title: 'Tickets',
      new: 'New ticket',
      loading: 'Loading tickets...',
      search: 'Search ticket...',
      deleteTitle: 'Delete ticket',
      deleteMessage: 'This ticket will be permanently removed. Continue?',
      saveError: 'Saving failed.',
      updated: 'Ticket updated',
      newNotification: 'New notification',
      statusFailed: 'Status update failed',
      dueDate: 'Due',
      writeMessage: 'Write a message...',
      noMessages: 'No messages',
      editTitle: 'Edit ticket',
      newTitle: 'New ticket',
    },
    benutzer: {
      title: 'Users',
      new: 'New user',
      loading: 'Loading users...',
      loadError: 'Users could not be loaded.',
      saveError: 'User could not be saved.',
      deleteError: 'User could not be deleted.',
      deleteTitle: 'Delete user',
      deleteMessage: 'This user will be permanently removed. Continue?',
      role: 'Role',
      editTitle: 'Edit user',
      newTitle: 'New user',
    },
    chat: {
      rooms: 'Chat rooms',
      noRooms: 'No rooms',
      chooseRoom: 'Choose a chat room',
      loadError: 'Rooms could not be loaded.',
      connect: 'Connect',
      writeMessage: 'Write a message...',
      user: 'User',
    },
    status: {
      Offen: 'Open',
      InBearbeitung: 'In progress',
      Geloest: 'Resolved',
      Geschlossen: 'Closed',
      NichtGestartet: 'Not started',
      Abgeschlossen: 'Completed',
      Pausiert: 'Paused',
      Niedrig: 'Low',
      Mittel: 'Medium',
      Hoch: 'High',
      Kritisch: 'Critical',
    },
  },
  de: {
    common: {
      search: 'Suchen',
      noData: 'Keine Daten vorhanden',
      previous: 'Zuruck',
      next: 'Weiter',
      confirm: 'Bitte bestaetigen',
      areYouSure: 'Sind Sie sicher?',
      delete: 'Loeschen',
      cancel: 'Abbrechen',
      save: 'Speichern',
      edit: 'Bearbeiten',
      add: 'Neu',
      loading: 'Laden...',
      actions: 'Aktionen',
      title: 'Titel',
      status: 'Status',
      priority: 'Prioritaet',
      category: 'Kategorie',
      messages: 'Nachrichten',
      send: 'Senden',
      reconnect: 'Verbinden',
      online: 'Online',
      profile: 'Profil',
      logout: 'Abmelden',
      closeMenu: 'Menue schliessen',
    },
    header: {
      welcome: 'Willkommen',
      system: 'System',
      light: 'Hell',
      dark: 'Dunkel',
      expandMenu: 'Menue erweitern',
      collapseMenu: 'Menue verkleinern',
      openMenu: 'Menue oeffnen',
      language: 'Sprache',
    },
    sidebar: {
      eyebrow: 'Vista Core',
      title: 'CRM Workspace',
      footer: 'Mandantenpanel',
      dashboard: 'Dashboard',
      kunden: 'Kunden',
      projekte: 'Projekte',
      tickets: 'Tickets',
      benutzer: 'Benutzer',
      chat: 'Chat',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Anmelden',
      email: 'E-Mail',
      password: 'Passwort',
      loginFailed: 'Anmeldung fehlgeschlagen.',
      twoFactor: 'Zwei-Faktor',
      codeSent: 'Ein Bestaetigungscode wurde gesendet an',
      codeLabel: '6-stelliger Code',
      verify: 'Bestaetigen',
      invalidCode: 'Code ungueltig oder abgelaufen.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'Alle',
      refresh: 'Aktualisieren',
      loading: 'Dashboard-Daten werden geladen...',
      error: 'Dashboard-Daten konnten nicht geladen werden.',
      empty: 'Keine Daten zum Anzeigen.',
      kundenAnzahl: 'Kunden',
      projekteAnzahl: 'Projekte',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Offene Tickets',
      benutzerAnzahl: 'Benutzer',
      berichteAnzahl: 'Berichte',
      aktiveProjekte: 'Aktive Projekte',
      kritischeTickets: 'Kritische Tickets',
    },
    kunden: {
      title: 'Kunden',
      new: 'Neuer Kunde',
      loading: 'Kunden werden geladen...',
      search: 'Kunde suchen...',
      deleteTitle: 'Kunde loeschen',
      deleteMessage: 'Dieser Datensatz wird dauerhaft entfernt. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      company: 'Unternehmen',
      firstName: 'Vorname',
      lastName: 'Nachname',
      phone: 'Telefon',
      mobilePhone: 'Telefon (Mobil)',
      homePhone: 'Telefon (Haus)',
      address: 'Adresse',
      website: 'Website',
      notes: 'Hinweise',
      editTitle: 'Kunde bearbeiten',
      newTitle: 'Neuer Kunde',
    },
    projekte: {
      title: 'Projekte',
      new: 'Neues Projekt',
      loading: 'Projekte werden geladen...',
      search: 'Projekt suchen...',
      deleteTitle: 'Projekt loeschen',
      deleteMessage: 'Projekt wird dauerhaft geloescht. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      name: 'Name',
      description: 'Beschreibung',
      start: 'Start',
      end: 'Ende',
      completion: 'Abschluss %',
      editTitle: 'Projekt bearbeiten',
      newTitle: 'Neues Projekt',
    },
    tickets: {
      title: 'Tickets',
      new: 'Neues Ticket',
      loading: 'Tickets werden geladen...',
      search: 'Ticket suchen...',
      deleteTitle: 'Ticket loeschen',
      deleteMessage: 'Dieses Ticket wird dauerhaft entfernt. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      updated: 'Ticket aktualisiert',
      newNotification: 'Neue Benachrichtigung',
      statusFailed: 'Statuswechsel fehlgeschlagen',
      dueDate: 'Faellig',
      writeMessage: 'Nachricht schreiben...',
      noMessages: 'Keine Nachrichten',
      editTitle: 'Ticket bearbeiten',
      newTitle: 'Neues Ticket',
    },
    benutzer: {
      title: 'Benutzer',
      new: 'Neu',
      loading: 'Benutzer werden geladen...',
      loadError: 'Benutzer konnten nicht geladen werden.',
      saveError: 'Benutzer konnte nicht gespeichert werden.',
      deleteError: 'Benutzer konnte nicht geloescht werden.',
      deleteTitle: 'Benutzer loeschen',
      deleteMessage: 'Dieser Benutzer wird dauerhaft entfernt. Fortfahren?',
      role: 'Rolle',
      editTitle: 'Benutzer bearbeiten',
      newTitle: 'Neuer Benutzer',
    },
    chat: {
      rooms: 'Chat-Raeume',
      noRooms: 'Keine Raeume',
      chooseRoom: 'Waehlen Sie einen Chat-Raum',
      loadError: 'Raeume konnten nicht geladen werden.',
      connect: 'Verbinden',
      writeMessage: 'Nachricht schreiben...',
      user: 'Benutzer',
    },
    status: {
      Offen: 'Offen',
      InBearbeitung: 'In Bearbeitung',
      Geloest: 'Geloest',
      Geschlossen: 'Geschlossen',
      NichtGestartet: 'Nicht gestartet',
      Abgeschlossen: 'Abgeschlossen',
      Pausiert: 'Pausiert',
      Niedrig: 'Niedrig',
      Mittel: 'Mittel',
      Hoch: 'Hoch',
      Kritisch: 'Kritisch',
    },
  },
  fr: {
    common: {
      search: 'Rechercher',
      noData: 'Aucune donnee disponible',
      previous: 'Precedent',
      next: 'Suivant',
      confirm: 'Veuillez confirmer',
      areYouSure: 'Etes-vous sur ?',
      delete: 'Supprimer',
      cancel: 'Annuler',
      save: 'Enregistrer',
      edit: 'Modifier',
      add: 'Ajouter',
      loading: 'Chargement...',
      actions: 'Actions',
      title: 'Titre',
      status: 'Statut',
      priority: 'Priorite',
      category: 'Categorie',
      messages: 'Messages',
      send: 'Envoyer',
      reconnect: 'Reconnecter',
      online: 'En ligne',
      profile: 'Profil',
      logout: 'Se deconnecter',
      closeMenu: 'Fermer le menu',
    },
    header: {
      welcome: 'Bienvenue',
      system: 'Systeme',
      light: 'Clair',
      dark: 'Sombre',
      expandMenu: 'Etendre le menu',
      collapseMenu: 'Reduire le menu',
      openMenu: 'Ouvrir le menu',
      language: 'Langue',
    },
    sidebar: {
      eyebrow: 'Vista Core',
      title: 'Espace CRM',
      footer: 'Panneau locataire',
      dashboard: 'Tableau de bord',
      kunden: 'Clients',
      projekte: 'Projets',
      tickets: 'Tickets',
      benutzer: 'Utilisateurs',
      chat: 'Chat',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Connexion',
      email: 'E-mail',
      password: 'Mot de passe',
      loginFailed: 'Connexion echouee.',
      twoFactor: 'Double facteur',
      codeSent: 'Un code de verification a ete envoye a',
      codeLabel: 'Code a 6 chiffres',
      verify: 'Verifier',
      invalidCode: 'Code invalide ou expire.',
    },
    dashboard: {
      title: 'Tableau de bord',
      all: 'Tous',
      refresh: 'Actualiser',
      loading: 'Chargement des donnees du tableau de bord...',
      error: 'Impossible de charger les donnees du tableau de bord.',
      empty: 'Aucune donnee a afficher.',
      kundenAnzahl: 'Clients',
      projekteAnzahl: 'Projets',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Tickets ouverts',
      benutzerAnzahl: 'Utilisateurs',
      berichteAnzahl: 'Rapports',
      aktiveProjekte: 'Projets actifs',
      kritischeTickets: 'Tickets critiques',
    },
    kunden: {
      title: 'Clients',
      new: 'Nouveau client',
      loading: 'Chargement des clients...',
      search: 'Rechercher un client...',
      deleteTitle: 'Supprimer le client',
      deleteMessage: 'Cet enregistrement sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      company: 'Entreprise',
      firstName: 'Prenom',
      lastName: 'Nom',
      phone: 'Telephone',
      mobilePhone: 'Telephone portable',
      homePhone: 'Telephone domicile',
      address: 'Adresse',
      website: 'Site web',
      notes: 'Notes',
      editTitle: 'Modifier le client',
      newTitle: 'Nouveau client',
    },
    projekte: {
      title: 'Projets',
      new: 'Nouveau projet',
      loading: 'Chargement des projets...',
      search: 'Rechercher un projet...',
      deleteTitle: 'Supprimer le projet',
      deleteMessage: 'Le projet sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      name: 'Nom',
      description: 'Description',
      start: 'Debut',
      end: 'Fin',
      completion: 'Avancement %',
      editTitle: 'Modifier le projet',
      newTitle: 'Nouveau projet',
    },
    tickets: {
      title: 'Tickets',
      new: 'Nouveau ticket',
      loading: 'Chargement des tickets...',
      search: 'Rechercher un ticket...',
      deleteTitle: 'Supprimer le ticket',
      deleteMessage: 'Ce ticket sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      updated: 'Ticket mis a jour',
      newNotification: 'Nouvelle notification',
      statusFailed: 'Echec du changement de statut',
      dueDate: 'Echeance',
      writeMessage: 'Ecrire un message...',
      noMessages: 'Aucun message',
      editTitle: 'Modifier le ticket',
      newTitle: 'Nouveau ticket',
    },
    benutzer: {
      title: 'Utilisateurs',
      new: 'Nouvel utilisateur',
      loading: 'Chargement des utilisateurs...',
      loadError: 'Impossible de charger les utilisateurs.',
      saveError: 'Impossible d enregistrer l utilisateur.',
      deleteError: 'Impossible de supprimer l utilisateur.',
      deleteTitle: 'Supprimer l utilisateur',
      deleteMessage: 'Cet utilisateur sera supprime definitivement. Continuer ?',
      role: 'Role',
      editTitle: 'Modifier l utilisateur',
      newTitle: 'Nouvel utilisateur',
    },
    chat: {
      rooms: 'Salles de chat',
      noRooms: 'Aucune salle',
      chooseRoom: 'Choisissez une salle de chat',
      loadError: 'Impossible de charger les salles.',
      connect: 'Connecter',
      writeMessage: 'Ecrire un message...',
      user: 'Utilisateur',
    },
    status: {
      Offen: 'Ouvert',
      InBearbeitung: 'En cours',
      Geloest: 'Resolue',
      Geschlossen: 'Ferme',
      NichtGestartet: 'Non commence',
      Abgeschlossen: 'Termine',
      Pausiert: 'En pause',
      Niedrig: 'Faible',
      Mittel: 'Moyenne',
      Hoch: 'Haute',
      Kritisch: 'Critique',
    },
  },
  it: {
    common: {
      search: 'Cerca',
      noData: 'Nessun dato disponibile',
      previous: 'Precedente',
      next: 'Successivo',
      confirm: 'Conferma',
      areYouSure: 'Sei sicuro?',
      delete: 'Elimina',
      cancel: 'Annulla',
      save: 'Salva',
      edit: 'Modifica',
      add: 'Aggiungi',
      loading: 'Caricamento...',
      actions: 'Azioni',
      title: 'Titolo',
      status: 'Stato',
      priority: 'Priorita',
      category: 'Categoria',
      messages: 'Messaggi',
      send: 'Invia',
      reconnect: 'Riconnetti',
      online: 'Online',
      profile: 'Profilo',
      logout: 'Esci',
      closeMenu: 'Chiudi menu',
    },
    header: {
      welcome: 'Benvenuto',
      system: 'Sistema',
      light: 'Chiaro',
      dark: 'Scuro',
      expandMenu: 'Espandi menu',
      collapseMenu: 'Riduci menu',
      openMenu: 'Apri menu',
      language: 'Lingua',
    },
    sidebar: {
      eyebrow: 'Vista Core',
      title: 'Workspace CRM',
      footer: 'Pannello tenant',
      dashboard: 'Dashboard',
      kunden: 'Clienti',
      projekte: 'Progetti',
      tickets: 'Ticket',
      benutzer: 'Utenti',
      chat: 'Chat',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Accedi',
      email: 'E-mail',
      password: 'Password',
      loginFailed: 'Accesso non riuscito.',
      twoFactor: 'Due fattori',
      codeSent: 'Un codice di verifica e stato inviato a',
      codeLabel: 'Codice a 6 cifre',
      verify: 'Verifica',
      invalidCode: 'Codice non valido o scaduto.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'Tutti',
      refresh: 'Aggiorna',
      loading: 'Caricamento dati dashboard...',
      error: 'Impossibile caricare i dati della dashboard.',
      empty: 'Nessun dato da mostrare.',
      kundenAnzahl: 'Clienti',
      projekteAnzahl: 'Progetti',
      ticketsAnzahl: 'Ticket',
      offeneTickets: 'Ticket aperti',
      benutzerAnzahl: 'Utenti',
      berichteAnzahl: 'Report',
      aktiveProjekte: 'Progetti attivi',
      kritischeTickets: 'Ticket critici',
    },
    kunden: {
      title: 'Clienti',
      new: 'Nuovo cliente',
      loading: 'Caricamento clienti...',
      search: 'Cerca cliente...',
      deleteTitle: 'Elimina cliente',
      deleteMessage: 'Questo record verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      company: 'Azienda',
      firstName: 'Nome',
      lastName: 'Cognome',
      phone: 'Telefono',
      mobilePhone: 'Telefono mobile',
      homePhone: 'Telefono casa',
      address: 'Indirizzo',
      website: 'Sito web',
      notes: 'Note',
      editTitle: 'Modifica cliente',
      newTitle: 'Nuovo cliente',
    },
    projekte: {
      title: 'Progetti',
      new: 'Nuovo progetto',
      loading: 'Caricamento progetti...',
      search: 'Cerca progetto...',
      deleteTitle: 'Elimina progetto',
      deleteMessage: 'Il progetto verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      name: 'Nome',
      description: 'Descrizione',
      start: 'Inizio',
      end: 'Fine',
      completion: 'Completamento %',
      editTitle: 'Modifica progetto',
      newTitle: 'Nuovo progetto',
    },
    tickets: {
      title: 'Ticket',
      new: 'Nuovo ticket',
      loading: 'Caricamento ticket...',
      search: 'Cerca ticket...',
      deleteTitle: 'Elimina ticket',
      deleteMessage: 'Questo ticket verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      updated: 'Ticket aggiornato',
      newNotification: 'Nuova notifica',
      statusFailed: 'Aggiornamento stato non riuscito',
      dueDate: 'Scadenza',
      writeMessage: 'Scrivi un messaggio...',
      noMessages: 'Nessun messaggio',
      editTitle: 'Modifica ticket',
      newTitle: 'Nuovo ticket',
    },
    benutzer: {
      title: 'Utenti',
      new: 'Nuovo utente',
      loading: 'Caricamento utenti...',
      loadError: 'Impossibile caricare gli utenti.',
      saveError: 'Impossibile salvare l utente.',
      deleteError: 'Impossibile eliminare l utente.',
      deleteTitle: 'Elimina utente',
      deleteMessage: 'Questo utente verra eliminato definitivamente. Continuare?',
      role: 'Ruolo',
      editTitle: 'Modifica utente',
      newTitle: 'Nuovo utente',
    },
    chat: {
      rooms: 'Stanze chat',
      noRooms: 'Nessuna stanza',
      chooseRoom: 'Seleziona una stanza chat',
      loadError: 'Impossibile caricare le stanze.',
      connect: 'Connetti',
      writeMessage: 'Scrivi un messaggio...',
      user: 'Utente',
    },
    status: {
      Offen: 'Aperto',
      InBearbeitung: 'In corso',
      Geloest: 'Risolto',
      Geschlossen: 'Chiuso',
      NichtGestartet: 'Non iniziato',
      Abgeschlossen: 'Completato',
      Pausiert: 'In pausa',
      Niedrig: 'Bassa',
      Mittel: 'Media',
      Hoch: 'Alta',
      Kritisch: 'Critico',
    },
  },
};

function getValue(object, path) {
  return path.split('.').reduce((current, key) => current?.[key], object);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'de');

  const value = useMemo(() => ({
    language,
    setLanguage: (nextLanguage) => {
      setLanguage(nextLanguage);
      localStorage.setItem('language', nextLanguage);
    },
    options: languageOptions,
    t: (path, fallback = '') => getValue(translations[language], path) || fallback || path,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}