import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);

export const languageOptions = [
  { code: 'en', countryCode: 'gb', label: 'En' },
  { code: 'de', countryCode: 'de', label: 'De' },
  { code: 'fr', countryCode: 'fr', label: 'Fr' },
  { code: 'it', countryCode: 'it', label: 'It' },
];

const translations = {
  en: {
    common: {
      search: 'Search',
      copy: 'Copy',
      copied: 'Copied!',
      exportCsv: 'CSV',
      exportPdf: 'PDF',
      print: 'Print',
      noData: 'No data available',
      previous: 'Previous',
      next: 'Next',
      confirm: 'Please confirm',
      areYouSure: 'Are you sure?',
      delete: 'Delete',
      cancel: 'Cancel',
      save: 'Save',
      edit: 'Edit',
      add: 'Add',
      loading: 'Loading...',
      actions: 'Actions',
      title: 'Title',
      status: 'Status',
      priority: 'Priority',
      category: 'Category',
      messages: 'Messages',
      send: 'Send',
      reconnect: 'Reconnect',
      online: 'Online',
      profile: 'Profile',
      logout: 'Log out',
      closeMenu: 'Close menu',
      close: 'Close',
      reset: 'Reset',
      settings: 'Settings',
      select: 'Select',
      selected: 'selected',
    },
    header: {
      welcome: 'Welcome',
      system: 'System',
      light: 'Light',
      dark: 'Dark',
      expandMenu: 'Expand menu',
      collapseMenu: 'Collapse menu',
      openMenu: 'Open menu',
      language: 'Language',
      themeSettings: 'Theme Settings',
      themeSettingsDesc: 'Tune appearance and layout.',
      themeMode: 'Theme mode',
      themeModeDesc: 'Choose the visual mode for your workspace.',
      activeTheme: 'Active theme',
      sidebarStyle: 'Sidebar style',
      sidebarStyleDesc: 'Switch between Sidebar, Inset and Floating.',
      sidebarStyleSidebar: 'Sidebar',
      sidebarStyleInset: 'Inset',
      sidebarStyleFloating: 'Floating',
      layoutMode: 'Layout mode',
      layoutModeDesc: 'Choose Default, Compact or Full density.',
      layoutDefault: 'Default',
      layoutCompact: 'Compact',
      layoutFull: 'Full',
      sidebar: 'Sidebar',
      sidebarDesc: 'Control how navigation appears.',
      sidebarCollapsed: 'Collapsed sidebar',
      sidebarCollapsedDesc: 'Show icon-only sidebar on desktop',
    },
    sidebar: {
      eyebrow: 'Vista.CoreX',
      title: 'CRM Workspace',
      footer: 'Tenant panel',
      dashboard: 'Dashboard',
      kunden: 'Customers',
      projekte: 'Projects',
      tickets: 'Tickets',
      benutzer: 'Users',
      berichte: 'Reports',
      chat: 'Chat',
      management: 'Management',
      system: 'System',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Sign in',
      email: 'E-Mail',
      password: 'Password',
      loginFailed: 'Sign in failed.',
      twoFactor: 'Two-Factor',
      codeSent: 'A verification code was sent to',
      codeLabel: '6-digit code',
      verify: 'Verify',
      invalidCode: 'Code is invalid or expired.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'All',
      refresh: 'Refresh',
      loading: 'Loading dashboard data...',
      error: 'Dashboard data could not be loaded.',
      empty: 'No data to display.',
      kundenAnzahl: 'Customers',
      projekteAnzahl: 'Projects',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Open tickets',
      benutzerAnzahl: 'Users',
      berichteAnzahl: 'Reports',
      aktiveProjekte: 'Active projects',
      kritischeTickets: 'Critical tickets',
    },
    kunden: {
      title: 'Customers',
      new: 'New customer',
      loading: 'Loading customers...',
      search: 'Search customer...',
      deleteTitle: 'Delete customer',
      deleteMessage: 'This record will be permanently removed. Continue?',
      saveError: 'Saving failed.',
      company: 'Company',
      firstName: 'First name',
      lastName: 'Last name',
      phone: 'Phone',
      mobilePhone: 'Phone (mobile)',
      homePhone: 'Phone (home)',
      address: 'Address',
      website: 'Website',
      notes: 'Notes',
      editTitle: 'Edit customer',
      newTitle: 'New customer',
    },
    projekte: {
      title: 'Projects',
      new: 'New project',
      loading: 'Loading projects...',
      search: 'Search project...',
      deleteTitle: 'Delete project',
      deleteMessage: 'Project will be permanently deleted. Continue?',
      saveError: 'Saving failed.',
      name: 'Name',
      description: 'Description',
      start: 'Start',
      end: 'End',
      completion: 'Completion %',
      editTitle: 'Edit project',
      newTitle: 'New project',
      noProjects: 'No projects available',
      projekteFor: 'Projects',
      goToProject: 'Go to Project',
      assignedUsers: 'Assigned Users',
      minOneUser: 'At least one user must be assigned!',
      ansprechpartner: 'Contact Persons',
      minOneAnsprechpartner: 'At least one contact person must be assigned!',
    },
    tickets: {
      title: 'Tickets',
      new: 'New ticket',
      loading: 'Loading tickets...',
      search: 'Search ticket...',
      deleteTitle: 'Delete ticket',
      deleteMessage: 'This ticket will be permanently removed. Continue?',
      saveError: 'Saving failed.',
      updated: 'Ticket updated',
      newNotification: 'New notification',
      statusFailed: 'Status update failed',
      dueDate: 'Due',
      writeMessage: 'Write a message...',
      noMessages: 'No messages',
      editTitle: 'Edit ticket',
      newTitle: 'New ticket',
    },
    benutzer: {
      title: 'Users',
      new: 'New user',
      loading: 'Loading users...',
      loadError: 'Users could not be loaded.',
      saveError: 'User could not be saved.',
      deleteError: 'User could not be deleted.',
      deleteTitle: 'Delete user',
      deleteMessage: 'This user will be permanently removed. Continue?',
      role: 'Role',
      abteilung: 'Department',
      rufNummer: 'Phone',
      editTitle: 'Edit user',
      viewTitle: 'User Details',
      newTitle: 'New user',
      search: 'Search users...',
      noUsers: 'No users available',
    },
    chat: {
      rooms: 'Chat rooms',
      noRooms: 'No rooms',
      chooseRoom: 'Choose a chat room',
      loadError: 'Rooms could not be loaded.',
      connect: 'Connect',
      writeMessage: 'Write a message...',
      user: 'User',
    },
    status: {
      Offen: 'Open',
      InBearbeitung: 'In progress',
      Geloest: 'Resolved',
      Geschlossen: 'Closed',
      NichtGestartet: 'Not started',
      Abgeschlossen: 'Completed',
      Pausiert: 'Paused',
      Niedrig: 'Low',
      Mittel: 'Medium',
      Hoch: 'High',
      Kritisch: 'Critical',
    },
    errors: {
      badRequest: 'Invalid Request',
      unauthorized: 'Authentication Required',
      forbidden: 'Access Denied',
      notFound: 'Resource Not Found',
      conflict: 'Conflict: Resource Already Exists',
      validationError: 'Validation Error',
      serverError: 'Server Error',
      serviceUnavailable: 'Service Temporarily Unavailable',
      networkError: 'Network Error: Cannot Connect to Server',
      unknownError: 'Unknown Error',
    },
  },
  de: {
    common: {
      search: 'Suchen',
      copy: 'Kopieren',
      copied: 'Kopiert!',
      exportCsv: 'CSV',
      exportPdf: 'PDF',
      print: 'Drucken',
      noData: 'Keine Daten vorhanden',
      previous: 'Zuruck',
      next: 'Weiter',
      confirm: 'Bitte bestaetigen',
      areYouSure: 'Sind Sie sicher?',
      delete: 'Loeschen',
      cancel: 'Abbrechen',
      save: 'Speichern',
      edit: 'Bearbeiten',
      add: 'Neu',
      loading: 'Laden...',
      actions: 'Aktionen',
      title: 'Titel',
      status: 'Status',
      priority: 'Prioritaet',
      category: 'Kategorie',
      messages: 'Nachrichten',
      send: 'Senden',
      reconnect: 'Verbinden',
      online: 'Online',
      profile: 'Profil',
      logout: 'Abmelden',
      closeMenu: 'Menue schliessen',
      close: 'Schliessen',
      reset: 'Zuruecksetzen',
      settings: 'Einstellungen',
      select: 'Auswaehlen',
      selected: 'ausgewaehlt',
    },
    header: {
      welcome: 'Willkommen',
      system: 'System',
      light: 'Hell',
      dark: 'Dunkel',
      expandMenu: 'Menue erweitern',
      collapseMenu: 'Menue verkleinern',
      openMenu: 'Menue oeffnen',
      language: 'Sprache',
      themeSettings: 'Darstellungseinstellungen',
      themeSettingsDesc: 'Erscheinungsbild und Layout anpassen.',
      themeMode: 'Farbschema',
      themeModeDesc: 'Waehlen Sie den visuellen Modus.',
      activeTheme: 'Aktives Design',
      sidebarStyle: 'Sidebar-Stil',
      sidebarStyleDesc: 'Zwischen Sidebar, Eingebettet und Schwebend wechseln.',
      sidebarStyleSidebar: 'Sidebar',
      sidebarStyleInset: 'Eingebettet',
      sidebarStyleFloating: 'Schwebend',
      layoutMode: 'Layout-Modus',
      layoutModeDesc: 'Standard, Kompakt oder Vollbild waehlen.',
      layoutDefault: 'Standard',
      layoutCompact: 'Kompakt',
      layoutFull: 'Vollbild',
      sidebar: 'Sidebar',
      sidebarDesc: 'Standarddarstellung der Navigation.',
      sidebarCollapsed: 'Sidebar eingeklappt',
      sidebarCollapsedDesc: 'Nur Icons auf dem Desktop anzeigen',
    },
    sidebar: {
      eyebrow: 'Vista.CoreX',
      title: 'CRM Workspace',
      footer: 'Mandantenpanel',
      dashboard: 'Dashboard',
      kunden: 'Kunden',
      projekte: 'Projekte',
      tickets: 'Tickets',
      benutzer: 'Benutzer',
      berichte: 'Berichte',
      chat: 'Chat',
      management: 'Verwaltung',
      system: 'System',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Anmelden',
      email: 'E-Mail',
      password: 'Passwort',
      loginFailed: 'Anmeldung fehlgeschlagen.',
      twoFactor: 'Zwei-Faktor',
      codeSent: 'Ein Bestaetigungscode wurde gesendet an',
      codeLabel: '6-stelliger Code',
      verify: 'Bestaetigen',
      invalidCode: 'Code ungueltig oder abgelaufen.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'Alle',
      refresh: 'Aktualisieren',
      loading: 'Dashboard-Daten werden geladen...',
      error: 'Dashboard-Daten konnten nicht geladen werden.',
      empty: 'Keine Daten zum Anzeigen.',
      kundenAnzahl: 'Kunden',
      projekteAnzahl: 'Projekte',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Offene Tickets',
      benutzerAnzahl: 'Benutzer',
      berichteAnzahl: 'Berichte',
      aktiveProjekte: 'Aktive Projekte',
      kritischeTickets: 'Kritische Tickets',
    },
    kunden: {
      title: 'Kunden',
      new: 'Neuer Kunde',
      loading: 'Kunden werden geladen...',
      search: 'Kunde suchen...',
      deleteTitle: 'Kunde loeschen',
      deleteMessage: 'Dieser Datensatz wird dauerhaft entfernt. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      company: 'Unternehmen',
      firstName: 'Vorname',
      lastName: 'Nachname',
      phone: 'Telefon',
      mobilePhone: 'Telefon (Mobil)',
      homePhone: 'Telefon (Haus)',
      address: 'Adresse',
      website: 'Website',
      notes: 'Hinweise',
      editTitle: 'Kunde bearbeiten',
      newTitle: 'Neuer Kunde',
    },
    projekte: {
      title: 'Projekte',
      new: 'Neues Projekt',
      loading: 'Projekte werden geladen...',
      search: 'Projekt suchen...',
      deleteTitle: 'Projekt loeschen',
      deleteMessage: 'Projekt wird dauerhaft geloescht. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      name: 'Name',
      description: 'Beschreibung',
      start: 'Start',
      end: 'Ende',
      completion: 'Abschluss %',
      editTitle: 'Projekt bearbeiten',
      newTitle: 'Neues Projekt',
      noProjects: 'Keine Projekte vorhanden',
      projekteFor: 'Projekte',
      goToProject: 'Zum Projekt',
      assignedUsers: 'Zugewiesen',
      minOneUser: 'Mindestens ein Benutzer muss zugewiesen werden!',
      ansprechpartner: 'Ansprechpartner',
      minOneAnsprechpartner: 'Mindestens ein Ansprechpartner muss zugewiesen werden!',
    },
    tickets: {
      title: 'Tickets',
      new: 'Neues Ticket',
      loading: 'Tickets werden geladen...',
      search: 'Ticket suchen...',
      deleteTitle: 'Ticket loeschen',
      deleteMessage: 'Dieses Ticket wird dauerhaft entfernt. Fortfahren?',
      saveError: 'Fehler beim Speichern.',
      updated: 'Ticket aktualisiert',
      newNotification: 'Neue Benachrichtigung',
      statusFailed: 'Statuswechsel fehlgeschlagen',
      dueDate: 'Faellig',
      writeMessage: 'Nachricht schreiben...',
      noMessages: 'Keine Nachrichten',
      editTitle: 'Ticket bearbeiten',
      newTitle: 'Neues Ticket',
    },
    benutzer: {
      title: 'Benutzer',
      new: 'Neu',
      loading: 'Benutzer werden geladen...',
      loadError: 'Benutzer konnten nicht geladen werden.',
      saveError: 'Benutzer konnte nicht gespeichert werden.',
      deleteError: 'Benutzer konnte nicht geloescht werden.',
      deleteTitle: 'Benutzer loeschen',
      deleteMessage: 'Dieser Benutzer wird dauerhaft entfernt. Fortfahren?',
      role: 'Rolle',
      abteilung: 'Abteilung',
      rufNummer: 'Rufnummer',
      editTitle: 'Benutzer bearbeiten',
      viewTitle: 'Benutzer Details',
      newTitle: 'Neuer Benutzer',
      search: 'Benutzer suchen...',
      noUsers: 'Keine Benutzer verfuegbar',
    },
    chat: {
      rooms: 'Chat-Raeume',
      noRooms: 'Keine Raeume',
      chooseRoom: 'Waehlen Sie einen Chat-Raum',
      loadError: 'Raeume konnten nicht geladen werden.',
      connect: 'Verbinden',
      writeMessage: 'Nachricht schreiben...',
      user: 'Benutzer',
    },
    status: {
      Offen: 'Offen',
      InBearbeitung: 'In Bearbeitung',
      Geloest: 'Geloest',
      Geschlossen: 'Geschlossen',
      NichtGestartet: 'Nicht gestartet',
      Abgeschlossen: 'Abgeschlossen',
      Pausiert: 'Pausiert',
      Niedrig: 'Niedrig',
      Mittel: 'Mittel',
      Hoch: 'Hoch',
      Kritisch: 'Kritisch',
    },
    errors: {
      badRequest: 'Ungültige Anfrage',
      unauthorized: 'Authentifizierung erforderlich',
      forbidden: 'Zugriff verweigert',
      notFound: 'Ressource nicht gefunden',
      conflict: 'Konflikt: Ressource existiert bereits',
      validationError: 'Validierungsfehler',
      serverError: 'Serverfehler',
      serviceUnavailable: 'Dienst vorübergehend nicht verfügbar',
      networkError: 'Netzwerkfehler: Verbindung zum Server nicht möglich',
      unknownError: 'Unbekannter Fehler',
    },
  },
  fr: {
    common: {
      search: 'Rechercher',
      copy: 'Copier',
      copied: 'Copié !',
      exportCsv: 'CSV',
      exportPdf: 'PDF',
      print: 'Imprimer',
      noData: 'Aucune donnee disponible',
      previous: 'Precedent',
      next: 'Suivant',
      confirm: 'Veuillez confirmer',
      areYouSure: 'Etes-vous sur ?',
      delete: 'Supprimer',
      cancel: 'Annuler',
      save: 'Enregistrer',
      edit: 'Modifier',
      add: 'Ajouter',
      loading: 'Chargement...',
      actions: 'Actions',
      title: 'Titre',
      status: 'Statut',
      priority: 'Priorite',
      category: 'Categorie',
      messages: 'Messages',
      send: 'Envoyer',
      reconnect: 'Reconnecter',
      online: 'En ligne',
      profile: 'Profil',
      logout: 'Se deconnecter',
      closeMenu: 'Fermer le menu',
      close: 'Fermer',
      reset: 'Reinitialiser',
      settings: 'Parametres',
      select: 'Selectionner',
      selected: 'selectionnees',
    },
    header: {
      welcome: 'Bienvenue',
      system: 'Systeme',
      light: 'Clair',
      dark: 'Sombre',
      expandMenu: 'Etendre le menu',
      collapseMenu: 'Reduire le menu',
      openMenu: 'Ouvrir le menu',
      language: 'Langue',
      themeSettings: 'Parametres d apparence',
      themeSettingsDesc: 'Personnalisez l apparence et la mise en page.',
      themeMode: 'Mode couleur',
      themeModeDesc: 'Choisissez le mode visuel de votre espace.',
      activeTheme: 'Theme actif',
      sidebarStyle: 'Style de la barre laterale',
      sidebarStyleDesc: 'Basculer entre Barre, Integre et Flottant.',
      sidebarStyleSidebar: 'Barre',
      sidebarStyleInset: 'Integre',
      sidebarStyleFloating: 'Flottant',
      layoutMode: 'Mode de mise en page',
      layoutModeDesc: 'Choisir Defaut, Compact ou Plein ecran.',
      layoutDefault: 'Defaut',
      layoutCompact: 'Compact',
      layoutFull: 'Plein ecran',
      sidebar: 'Barre laterale',
      sidebarDesc: 'Controler l affichage de la navigation.',
      sidebarCollapsed: 'Barre reduite',
      sidebarCollapsedDesc: 'Afficher uniquement les icones sur le bureau',
    },
    sidebar: {
      eyebrow: 'Vista.CoreX',
      title: 'Espace CRM',
      footer: 'Panneau locataire',
      dashboard: 'Tableau de bord',
      kunden: 'Clients',
      projekte: 'Projets',
      tickets: 'Tickets',
      benutzer: 'Utilisateurs',
      berichte: 'Rapports',
      chat: 'Chat',
      management: 'Gestion',
      system: 'Systeme',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Connexion',
      email: 'E-mail',
      password: 'Mot de passe',
      loginFailed: 'Connexion echouee.',
      twoFactor: 'Double facteur',
      codeSent: 'Un code de verification a ete envoye a',
      codeLabel: 'Code a 6 chiffres',
      verify: 'Verifier',
      invalidCode: 'Code invalide ou expire.',
    },
    dashboard: {
      title: 'Tableau de bord',
      all: 'Tous',
      refresh: 'Actualiser',
      loading: 'Chargement des donnees du tableau de bord...',
      error: 'Impossible de charger les donnees du tableau de bord.',
      empty: 'Aucune donnee a afficher.',
      kundenAnzahl: 'Clients',
      projekteAnzahl: 'Projets',
      ticketsAnzahl: 'Tickets',
      offeneTickets: 'Tickets ouverts',
      benutzerAnzahl: 'Utilisateurs',
      berichteAnzahl: 'Rapports',
      aktiveProjekte: 'Projets actifs',
      kritischeTickets: 'Tickets critiques',
    },
    kunden: {
      title: 'Clients',
      new: 'Nouveau client',
      loading: 'Chargement des clients...',
      search: 'Rechercher un client...',
      deleteTitle: 'Supprimer le client',
      deleteMessage: 'Cet enregistrement sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      company: 'Entreprise',
      firstName: 'Prenom',
      lastName: 'Nom',
      phone: 'Telephone',
      mobilePhone: 'Telephone portable',
      homePhone: 'Telephone domicile',
      address: 'Adresse',
      website: 'Site web',
      notes: 'Notes',
      editTitle: 'Modifier le client',
      newTitle: 'Nouveau client',
    },
    projekte: {
      title: 'Projets',
      new: 'Nouveau projet',
      loading: 'Chargement des projets...',
      search: 'Rechercher un projet...',
      deleteTitle: 'Supprimer le projet',
      deleteMessage: 'Le projet sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      name: 'Nom',
      description: 'Description',
      start: 'Debut',
      end: 'Fin',
      completion: 'Avancement %',
      editTitle: 'Modifier le projet',
      newTitle: 'Nouveau projet',
      noProjects: 'Aucun projet disponible',
      projekteFor: 'Projets',
      goToProject: 'Aller au projet',
      assignedUsers: 'Affectes',
      minOneUser: 'Au moins un utilisateur doit etre affecte !',
      ansprechpartner: 'Personnes de contact',
      minOneAnsprechpartner: 'Au moins une personne de contact doit etre affectee !',
    },
    tickets: {
      title: 'Tickets',
      new: 'Nouveau ticket',
      loading: 'Chargement des tickets...',
      search: 'Rechercher un ticket...',
      deleteTitle: 'Supprimer le ticket',
      deleteMessage: 'Ce ticket sera supprime definitivement. Continuer ?',
      saveError: 'Echec de l enregistrement.',
      updated: 'Ticket mis a jour',
      newNotification: 'Nouvelle notification',
      statusFailed: 'Echec du changement de statut',
      dueDate: 'Echeance',
      writeMessage: 'Ecrire un message...',
      noMessages: 'Aucun message',
      editTitle: 'Modifier le ticket',
      newTitle: 'Nouveau ticket',
    },
    benutzer: {
      title: 'Utilisateurs',
      new: 'Nouvel utilisateur',
      loading: 'Chargement des utilisateurs...',
      loadError: 'Impossible de charger les utilisateurs.',
      saveError: 'Impossible d enregistrer l utilisateur.',
      deleteError: 'Impossible de supprimer l utilisateur.',
      deleteTitle: 'Supprimer l utilisateur',
      deleteMessage: 'Cet utilisateur sera supprime definitivement. Continuer ?',
      role: 'Role',
      abteilung: 'Département',
      rufNummer: 'Téléphone',
      editTitle: 'Modifier l utilisateur',
      viewTitle: 'Détails de l utilisateur',
      newTitle: 'Nouvel utilisateur',
      search: 'Rechercher des utilisateurs...',
      noUsers: 'Aucun utilisateur disponible',
    },
    chat: {
      rooms: 'Salles de chat',
      noRooms: 'Aucune salle',
      chooseRoom: 'Choisissez une salle de chat',
      loadError: 'Impossible de charger les salles.',
      connect: 'Connecter',
      writeMessage: 'Ecrire un message...',
      user: 'Utilisateur',
    },
    status: {
      Offen: 'Ouvert',
      InBearbeitung: 'En cours',
      Geloest: 'Resolue',
      Geschlossen: 'Ferme',
      NichtGestartet: 'Non commence',
      Abgeschlossen: 'Termine',
      Pausiert: 'En pause',
      Niedrig: 'Faible',
      Mittel: 'Moyenne',
      Hoch: 'Haute',
      Kritisch: 'Critique',
    },
    errors: {
      badRequest: 'Requête invalide',
      unauthorized: 'Authentification requise',
      forbidden: 'Accès refusé',
      notFound: 'Ressource non trouvée',
      conflict: 'Conflit: la ressource existe déjà',
      validationError: 'Erreur de validation',
      serverError: 'Erreur serveur',
      serviceUnavailable: 'Service temporairement indisponible',
      networkError: 'Erreur réseau: Impossible de se connecter au serveur',
      unknownError: 'Erreur inconnue',
    },
  },
  it: {
    common: {
      search: 'Cerca',
      copy: 'Copia',
      copied: 'Copiato!',
      exportCsv: 'CSV',
      exportPdf: 'PDF',
      print: 'Stampa',
      noData: 'Nessun dato disponibile',
      previous: 'Precedente',
      next: 'Successivo',
      confirm: 'Conferma',
      areYouSure: 'Sei sicuro?',
      delete: 'Elimina',
      cancel: 'Annulla',
      save: 'Salva',
      edit: 'Modifica',
      add: 'Aggiungi',
      loading: 'Caricamento...',
      actions: 'Azioni',
      title: 'Titolo',
      status: 'Stato',
      priority: 'Priorita',
      category: 'Categoria',
      messages: 'Messaggi',
      send: 'Invia',
      reconnect: 'Riconnetti',
      online: 'Online',
      profile: 'Profilo',
      logout: 'Esci',
      closeMenu: 'Chiudi menu',
      close: 'Chiudi',
      reset: 'Ripristina',
      settings: 'Impostazioni',
      select: 'Seleziona',
      selected: 'selezionati',
    },
    header: {
      welcome: 'Benvenuto',
      system: 'Sistema',
      light: 'Chiaro',
      dark: 'Scuro',
      expandMenu: 'Espandi menu',
      collapseMenu: 'Riduci menu',
      openMenu: 'Apri menu',
      language: 'Lingua',
      themeSettings: 'Impostazioni aspetto',
      themeSettingsDesc: 'Personalizza aspetto e layout.',
      themeMode: 'Modalita colore',
      themeModeDesc: 'Scegli la modalita visiva del tuo spazio.',
      activeTheme: 'Tema attivo',
      sidebarStyle: 'Stile barra laterale',
      sidebarStyleDesc: 'Passa tra Barra, Incorporato e Fluttuante.',
      sidebarStyleSidebar: 'Barra',
      sidebarStyleInset: 'Incorporato',
      sidebarStyleFloating: 'Fluttuante',
      layoutMode: 'Modalita layout',
      layoutModeDesc: 'Scegli Predefinito, Compatto o Schermo intero.',
      layoutDefault: 'Predefinito',
      layoutCompact: 'Compatto',
      layoutFull: 'Schermo intero',
      sidebar: 'Barra laterale',
      sidebarDesc: 'Controlla come appare la navigazione.',
      sidebarCollapsed: 'Barra ridotta',
      sidebarCollapsedDesc: 'Mostra solo icone su desktop',
    },
    sidebar: {
      eyebrow: 'Vista.CoreX',
      title: 'Workspace CRM',
      footer: 'Pannello tenant',
      dashboard: 'Dashboard',
      kunden: 'Clienti',
      projekte: 'Progetti',
      tickets: 'Ticket',
      benutzer: 'Utenti',
      berichte: 'Rapporti',
      chat: 'Chat',
      management: 'Gestione',
      system: 'Sistema',
    },
    auth: {
      loginTitle: 'Vista CRM',
      signIn: 'Accedi',
      email: 'E-mail',
      password: 'Password',
      loginFailed: 'Accesso non riuscito.',
      twoFactor: 'Due fattori',
      codeSent: 'Un codice di verifica e stato inviato a',
      codeLabel: 'Codice a 6 cifre',
      verify: 'Verifica',
      invalidCode: 'Codice non valido o scaduto.',
    },
    dashboard: {
      title: 'Dashboard',
      all: 'Tutti',
      refresh: 'Aggiorna',
      loading: 'Caricamento dati dashboard...',
      error: 'Impossibile caricare i dati della dashboard.',
      empty: 'Nessun dato da mostrare.',
      kundenAnzahl: 'Clienti',
      projekteAnzahl: 'Progetti',
      ticketsAnzahl: 'Ticket',
      offeneTickets: 'Ticket aperti',
      benutzerAnzahl: 'Utenti',
      berichteAnzahl: 'Report',
      aktiveProjekte: 'Progetti attivi',
      kritischeTickets: 'Ticket critici',
    },
    kunden: {
      title: 'Clienti',
      new: 'Nuovo cliente',
      loading: 'Caricamento clienti...',
      search: 'Cerca cliente...',
      deleteTitle: 'Elimina cliente',
      deleteMessage: 'Questo record verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      company: 'Azienda',
      firstName: 'Nome',
      lastName: 'Cognome',
      phone: 'Telefono',
      mobilePhone: 'Telefono mobile',
      homePhone: 'Telefono casa',
      address: 'Indirizzo',
      website: 'Sito web',
      notes: 'Note',
      editTitle: 'Modifica cliente',
      newTitle: 'Nuovo cliente',
    },
    projekte: {
      title: 'Progetti',
      new: 'Nuovo progetto',
      loading: 'Caricamento progetti...',
      search: 'Cerca progetto...',
      deleteTitle: 'Elimina progetto',
      deleteMessage: 'Il progetto verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      name: 'Nome',
      description: 'Descrizione',
      start: 'Inizio',
      end: 'Fine',
      completion: 'Completamento %',
      editTitle: 'Modifica progetto',
      newTitle: 'Nuovo progetto',
      noProjects: 'Nessun progetto disponibile',
      projekteFor: 'Progetti',
      goToProject: 'Vai al progetto',
      assignedUsers: 'Assegnati',
      minOneUser: 'Almeno un utente deve essere assegnato!',
      ansprechpartner: 'Persone di contatto',
      minOneAnsprechpartner: 'Almeno una persona di contatto deve essere assegnata!',
    },
    tickets: {
      title: 'Ticket',
      new: 'Nuovo ticket',
      loading: 'Caricamento ticket...',
      search: 'Cerca ticket...',
      deleteTitle: 'Elimina ticket',
      deleteMessage: 'Questo ticket verra eliminato definitivamente. Continuare?',
      saveError: 'Salvataggio non riuscito.',
      updated: 'Ticket aggiornato',
      newNotification: 'Nuova notifica',
      statusFailed: 'Aggiornamento stato non riuscito',
      dueDate: 'Scadenza',
      writeMessage: 'Scrivi un messaggio...',
      noMessages: 'Nessun messaggio',
      editTitle: 'Modifica ticket',
      newTitle: 'Nuovo ticket',
    },
    benutzer: {
      title: 'Utenti',
      new: 'Nuovo utente',
      loading: 'Caricamento utenti...',
      loadError: 'Impossibile caricare gli utenti.',
      saveError: 'Impossibile salvare l utente.',
      deleteError: 'Impossibile eliminare l utente.',
      deleteTitle: 'Elimina utente',
      deleteMessage: 'Questo utente verra eliminato definitivamente. Continuare?',
      role: 'Ruolo',
      abteilung: 'Dipartimento',
      rufNummer: 'Telefono',
      editTitle: 'Modifica utente',
      viewTitle: 'Dettagli utente',
      newTitle: 'Nuovo utente',
      search: 'Cerca utenti...',
      noUsers: 'Nessun utente disponibile',
    },
    chat: {
      rooms: 'Stanze chat',
      noRooms: 'Nessuna stanza',
      chooseRoom: 'Seleziona una stanza chat',
      loadError: 'Impossibile caricare le stanze.',
      connect: 'Connetti',
      writeMessage: 'Scrivi un messaggio...',
      user: 'Utente',
    },
    status: {
      Offen: 'Aperto',
      InBearbeitung: 'In corso',
      Geloest: 'Risolto',
      Geschlossen: 'Chiuso',
      NichtGestartet: 'Non iniziato',
      Abgeschlossen: 'Completato',
      Pausiert: 'In pausa',
      Niedrig: 'Bassa',
      Mittel: 'Media',
      Hoch: 'Alta',
      Kritisch: 'Critico',
    },
    errors: {
      badRequest: 'Richiesta non valida',
      unauthorized: 'Autenticazione richiesta',
      forbidden: 'Accesso negato',
      notFound: 'Risorsa non trovata',
      conflict: 'Conflitto: La risorsa esiste già',
      validationError: 'Errore di convalida',
      serverError: 'Errore del server',
      serviceUnavailable: 'Servizio temporaneamente non disponibile',
      networkError: 'Errore di rete: Impossibile connettersi al server',
      unknownError: 'Errore sconosciuto',
    },
  },
};

function getValue(object, path) {
  return path.split('.').reduce((current, key) => current?.[key], object);
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'de');

  const value = useMemo(() => ({
    language,
    setLanguage: (nextLanguage) => {
      setLanguage(nextLanguage);
      localStorage.setItem('language', nextLanguage);
    },
    options: languageOptions,
    t: (path, fallback = '') => getValue(translations[language], path) || fallback || path,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }

  return context;
}